### ISSUE TITLE
You must set up the project dependencies

### ISSUE THREAD

**Issue by olpo24** [Laemmi/laemmi-yourls-default-tools#1]
Hallo,

ich habe die tools mit dem theme packet installiert:
composer require laemmi/laemmi-yourls-plugin-theme

Das Theme Plugin als solches lässt sich auch aktivieren, die Tools jedoch nicht, es erscheint:
You must set up the project dependencies, run the following commands: curl -s http://getcomposer.org/installer | php php composer.phar install

**Comment by Laemmi** [comment]
Hi,

vielen dank für das benutzen meiner plugins. 😀

Ich habe die tools aktualisiert, damit diese auch mit der aktuellen Yourls Version 1.7.6 funktionieren. Einfach `composer update` aufrufen

**Comment by olpo24** [comment]
Ich habe die tools aktualisiert, damit diese auch mit der aktuellen Yourls Version 1.7.6 funktionieren. Einfach `composer update` aufrufen

**Comment by Laemmi** [comment]
Blöd das nicht auf Anhieb klappt. Schau mal ob du das Verzeichnis `cache` hast und ob der Webuser da Schreibrechte hat.

**Comment by Laemmi** [comment]
close
